apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-webapp.fullname" . }}-backend
  labels:
    {{- include "my-webapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-webapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "my-webapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.backend.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml (coalesce .Values.backend.resources .Values.resources) | nindent 12 }}
          {{- if .Values.postgresql.enabled }}
          envFrom:
            - secretRef:
                name: {{ printf "%s-%s" .Release.Name "postgresql" }}
          {{- end }}
